### ISSUE TITLE
`TestBaza.test_push_compressed_content` test is not stable

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#105]
The test is not stable, I'm getting this sometimes:

```
TestBaza
  test_push_compression_disabled                                  PASS (0.01s)
  test_simple_recent_check                                        PASS (0.00s)
  test_real_http                                                  PASS (0.00s)
  test_push_with_big_meta                                         PASS (0.00s)
  test_simple_exists_check                                        PASS (0.00s)
  test_simple_pull                                                PASS (0.00s)
  test_simple_push                                                PASS (0.00s)
  test_push_compressed_content                                   ERROR (0.00s)
Minitest::UnexpectedError:         Zlib::GzipFile::NoFooter: footer is not found
            test/test_baza.rb:119:in `zcat'
            test/test_baza.rb:119:in `test_push_compressed_content'

  test_push_with_meta                                             PASS (0.00s)
```

**Comment by yegor256** [comment]
@tank-bohr maybe you can help?

**Comment by tank-bohr** [comment]
Hey @yegor256! I would help you with pleasure

- let's move this issue to https://github.com/zerocracy/baza.rb
- do you have a sample from CI?
- maybe you have a seed to help me reproduce?
- I tried it myself and didn't manage to reproduce

I used the script

```bash
for i in {1..100}; do rake test || break; done 
```

And everything is green. Maybe let's unskip it and try to monitor it on the CI

**Comment by yegor256** [comment]
@tank-bohr just did: https://github.com/zerocracy/baza.rb/commit/dfa9cb302c6cd60de3ff44932a14bebabb79462a
