### ISSUE TITLE
"\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#12]
```
error: "\x82" from ASCII-8BIT to UTF-8
/usr/local/bundle/gems/judges-0.0.13/lib/judges/commands/update.rb:66:in `write': "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /usr/local/bundle/gems/judges-0.0.13/lib/judges/commands/update.rb:66:in `run'
	from /usr/local/bundle/gems/judges-0.0.13/bin/judges:60:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /usr/local/bundle/gems/judges-0.0.13/bin/judges:91:in `<top (required)>'
	from /usr/local/bundle/bin/judges:25:in `load'
	from /usr/local/bundle/bin/judges:25:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.14`
