### ISSUE TITLE
undefined method `strip' for nil (NoMethodError)

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#13]
```
lib/judges/options.rb:54:in `block in method_missing': undefined method `strip' for nil (NoMethodError)

        k = p[0].strip
                ^^^^^^
	from /usr/local/bundle/gems/judges-0.0.14/lib/judges/options.rb:52:in `to_h'
	from /usr/local/bundle/gems/judges-0.0.14/lib/judges/options.rb:52:in `method_missing'
	from /usr/local/bundle/gems/judges-0.0.14/lib/judges/options.rb:38:in `to_s'
	from /usr/local/bundle/gems/judges-0.0.14/lib/judges/commands/update.rb:53:in `run'
	from /usr/local/bundle/gems/judges-0.0.14/bin/judges:60:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /usr/local/bundle/gems/judges-0.0.14/bin/judges:91:in `<top (required)>'
	from /usr/local/bundle/bin/judges:25:in `load'
	from /usr/local/bundle/bin/judges:25:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.15`
