### ISSUE TITLE
error with `opts['max-cycles']`

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#18]
```
if !opts['max-cycles'].nil? && c > opts['max-cycles']
                                         ^^^^^^^^^^^^^^^^^^
	from /usr/local/bundle/gems/judges-0.0.18/lib/judges/commands/update.rb:52:in `block in run'
	from <internal:kernel>:187:in `loop'
	from /usr/local/bundle/gems/judges-0.0.18/lib/judges/commands/update.rb:49:in `run'
	from /usr/local/bundle/gems/judges-0.0.18/bin/judges:65:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /usr/local/bundle/gems/judges-0.0.18/bin/judges:110:in `<top (required)>'
	from /usr/local/bundle/bin/judges:25:in `load'
	from /usr/local/bundle/bin/judges:25:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.19`
