### ISSUE TITLE
undefined local variable or method `opts`

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#27]
```
/usr/local/bundle/gems/judges-0.0.25/lib/judges/commands/update.rb:88:in `cycle': undefined local variable or method `opts' for an instance of Judges::Update (NameError)

      raise "Failed to update correctly (#{errors.size} errors)" unless opts['quiet']
                                                                        ^^^^
	from /usr/local/bundle/gems/judges-0.0.25/lib/judges/commands/update.rb:53:in `block in run'
	from <internal:kernel>:187:in `loop'
	from /usr/local/bundle/gems/judges-0.0.25/lib/judges/commands/update.rb:51:in `run'
	from /usr/local/bundle/gems/judges-0.0.25/bin/judges:70:in `block (2 levels) in <class:App>'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /usr/local/bundle/gems/judges-0.0.25/bin/judges:127:in `<top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.26`
