### ISSUE TITLE
NoMethodError: undefined method `split'

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#67]
```
NoMethodError: undefined method `split' for [:JUDGES_ACTION_VERSION, "0.0.0"]:Array
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/options.rb:71:in `block (2 levels) in <class:Options>'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/options.rb:70:in `map!'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/options.rb:70:in `block in <class:Options>'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/options.rb:43:in `+'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:124:in `test_one'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:72:in `block (3 levels) in run'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:57:in `each'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:57:in `block (2 levels) in run'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/judges.rb:51:in `block in each_with_index'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/judges.rb:42:in `block in each'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/judges.rb:40:in `each'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/judges.rb:40:in `each'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/judges.rb:50:in `each_with_index'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:53:in `block in run'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/elapsed.rb:28:in `elapsed'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/lib/judges/commands/test.rb:52:in `run'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/bin/judges:156:in `block (2 levels) in <class:App>'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	/Users/yb/.rvm/gems/ruby-3.2.1/gems/judges-0.13.1/bin/judges:203:in `<top (required)>'
	/Users/yb/.rvm/gems/ruby-3.2.1/bin/judges:25:in `load'
	/Users/yb/.rvm/gems/ruby-3.2.1/bin/judges:25:in `<main>'
	/Users/yb/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
	/Users/yb/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.2`
